<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net452;netstandard2.0;netstandard2.1</TargetFrameworks>
    <LangVersion>8.0</LangVersion>
    <PackageId>Peakflames.SharpBucket</PackageId>
    <Version>0.19.0</Version>
    <Authors>Mitja Bezenšek, Mickaël Nivet, Peakflames</Authors>
    <Company>Peakflames</Company>
    <Product>SharpBucket (peakflames fork)</Product>
    <Copyright>Copyright 2014-2021</Copyright>
    <Description>A .Net wrapper for the Bitbucket REST API. Fork of MitjaBezensek/SharpBucket.</Description>
    <PackageDescription>SharpBucket is a .Net wrapper (written in c#) for the Bitbucket's REST API. With it you can have all the data of your repositories / issues at your fingertips. This is the peakflames fork of MitjaBezensek/SharpBucket.</PackageDescription>
    <PackageTags>Bitbucket REST API C#</PackageTags>
    <PackageProjectUrl>https://github.com/peakflames/SharpBucket</PackageProjectUrl>
    <RepositoryUrl>https://github.com/peakflames/SharpBucket</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReleaseNotes>https://github.com/peakflames/SharpBucket/releases/tag/v$(Version)</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <DefineConstants>$(DefineConstants);CS_8</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Assets\icon.png" Link="icon.png" Pack="true" PackagePath="" />
    <Content Include="..\LICENSE" Link="LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RestSharp" Version="106.12.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net452'">
    <Reference Include="System.Net.http" />
  </ItemGroup>

</Project>
